language: node_js
node_js:
  - lates
cache:
  directories:
  - node_modules
script:
  - yarn run build
  - yarn test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: gatsby-blog
