backend:
  name: github
  repo: PavlyukVadim/pavlyuk.io
  branch: gatsby-blog

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { label: Path, name: path }
      - { label: Date, name: date, widget: date }
      - { label: Title, name: title }
      - { label: Category, name: category }

      - { label: MetaTitle, name: metaTitle }
      - { label: MetaDescription, name: metaDescription }
      - { label: MetaKeywords, name: metaKeywords }

      - { label: Hidden, name: hidden }
      - { label: Featured, name: featured }
      - { label: Featured Image, name: thumbnail, widget: image }
      - { label: Body, name: body, widget: markdown }
